version: '3.8'
services:
  db:
    image: postgres:16.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: prueba
    ports:
      -"5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST : db
      DB_PORT : 5432
      DB_USER : postgres
      DB_PASSWORD : root123
      DB_NAME : prueba
      JWT_SECRET : admin123
    depends_on:
      - db


  